### ISSUE TITLE
Server Error when trying to access branches on netbox-docker

### ISSUE THREAD

**Issue by BrynjarFAune** [netboxlabs/netbox-branching#183]
### Plugin Version

0.5.2

### NetBox Version

4.1.6

### Python Version

3.12.3

### Steps to Reproduce

Install a fresh netbox-docker instance following [this guide](https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins), and add the netboxlabs-netbox-branching plugin.

1. git clone netbox-docker
2. create files plugin_requirements.txt, Dockerfile-Plugins, docker-compose.override.yml, local_settings.py
3. add "netboxlabs-netbox-branching" to plugin_requirements.txt
4. copy the contents of local_settings.py from [here](https://github.com/netboxlabs/netbox-branching)
5. copy the contents of Dockerfile-Plugins from the top link.
6. add "netbox_branching" to the plugin list in config/plugins.py
7. docker-compose build --no-cache
8. docker-compose up -d
9. access the web interface
10. click Branching > Branches 
![image](https://github.com/user-attachments/assets/6feb6e36-de3d-4cf2-be8b-80dc4b8e31f9)

### Expected Behavior

To see the branches and be able to switch between them on the branches page.

### Observed Behavior

The branches plugin appears correct in the GUI,
but I get a server error when I try accessing the Branches page.

``` md
Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'is_active' into field. Choices are: applied_changes, bookmarks, changediff, comments, conflicts, created, custom_field_data, description, events, id, jobs, journal_entries, last_sync, last_updated, merged_by, merged_by_id, merged_time, name, owner, owner_id, schema_id, status, subscriptions, tagged_items, tags

Python version: 3.12.3
NetBox version: 4.1.6
Plugins: 
  netbox_branching: 0.5.2

If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.
```

**Comment by BrynjarFAune** [comment]
Thank you for pointing me to the discussion in[ #1316](https://github.com/netbox-community/netbox-docker/discussions/1316). I’ve reviewed it thoroughly, but there don’t appear to be any additional tweaks there that I hadn’t already implemented.

I’ve followed the guide, and the containers are running without issues. I’m also able to create branches in the GUI, and right after creating a branch, I can perform actions like activating, deactivating, merging, or deleting it. However, once I navigate away, I lose access to the branch-specific pages because the Branches page (`Branching > Branches`) fails to load and displays a server error.

The error indicates that something on the main Branches page is attempting to query a nonexistent field (`is_active`). I assume this field should have been set up by the plugin at some point, but for some reason, it hasn’t been created in my instance.

Let me know if there are further debugging steps or adjustments I should try.


![image](https://github.com/user-attachments/assets/34048e44-4bac-4159-b580-c05aada90a95)

**Comment by cruse1977** [comment]
as an update on this I've been using branching in docker this evening without issue - so I've been unable to replicate this. 

**Dockerfile-Plugins**
```
FROM netboxcommunity/netbox:v4.1.8
RUN /opt/netbox/venv/bin/pip install netboxlabs-netbox-branching
COPY local_settings.py /opt/netbox/netbox/netbox/local_settings.py
```

**docker-compose.override.yml**

```
version: '3.4' # This is NOT the version of NetBox! No need to adjust :)
services:
  netbox:
    image: netbox:latest-plugins
    pull_policy: never
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    volumes:
      - ./plugins/:/plugins
  netbox-worker:
    image: netbox:latest-plugins
    pull_policy: never
  netbox-housekeeping:
    image: netbox:latest-plugins
    pull_policy: never

```
